#!/usr/bin/env bash

# COLORS
COLOR_RED='\e[31m'
COLOR_GREEN='\e[32m'
COLOR_BLUE='\e[94m'
COLOR_CYAN='\e[96m'
COLOR_YELLOW='\e[93m'
COLOR_ORANGE='\e[33m'
COLOR_PURPLE='\e[35m'
COLOR_PINK='\e[95m'
COLOR_WHITE='\e[39m'

# FONTS
FONT_BOLD='\e[1m'
FONT_UNDERLINED='\e[4m'
FONT_HIDDEN='\e[8m'

CLEAR='\e[0m' #CLEAR COLORS and FONTS